name: CD
on:
    push:
        branches:
            - master

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Deployment
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
        with:
          args: --script 'cd /var/www/alplast/' --script 'git checkout -f' --script 'git pull' --script 'composer update' --script 'npm run prod' --script 'php artisan migrate --force'
